# Generated by Django 4.0.2 on 2022-02-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mus_search', '0002_rename_title_music_entry_artistid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_entry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='music_entry',
            name='published',
        ),
        migrations.AddField(
            model_name='music_entry',
            name='artistName',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='music_entry',
            name='collectionName',
            field=models.CharField(default='', max_length=70),
        ),
    ]
