# Generated by Django 4.0.2 on 2022-02-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mus_search', '0003_remove_music_entry_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_entry',
            name='artworkUrl100',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='music_entry',
            name='collectionPrice',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='music_entry',
            name='country',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='music_entry',
            name='kind',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='music_entry',
            name='previewUrl',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='music_entry',
            name='primaryGenreName',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='music_entry',
            name='collectionName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
