# Generated by Django 4.0.2 on 2022-02-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mus_search', '0004_music_entry_artworkurl100_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_entry',
            name='trackId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='music_entry',
            name='collectionName',
            field=models.CharField(default='', max_length=70),
        ),
    ]
