# Generated by Django 4.0.2 on 2022-02-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mus_search', '0005_music_entry_trackid_alter_music_entry_collectionname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_entry',
            name='artistId',
        ),
    ]
